version: "3"
services:
  api_dev:
    image: edsonsousa33/api-ts
    ports:
      - "5000:3050"
    links:
      - link-db
  link-db:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
  client_dev:
    image: edsonsousa33/client-ts
    ports:
      - "3001:3000"
    links: 
      - api_dev
